// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mykomhnyvbnvpbyhukaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15a29taG55dmJudnBieWh1a2FxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3Mzg3NTcsImV4cCI6MjA3MjMxNDc1N30.Gi8kOMDR5Ks-73SXc4hDV4AgPbs-XRpUa6C8zcmlZ1U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});